[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Off"

[mouse]
hide_when_typing = true
